In [1]:
import numpy as np

In [2]:
sample_list=[6,7,9]
np.array(sample_list)

array([6, 7, 9])

In [3]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [5]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(1,9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [9]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [20]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
np.zeros(6,int)

array([0, 0, 0, 0, 0, 0])

In [22]:
np.ones(9,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1])

In [23]:
np.ones((3,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [24]:
np.ones((1,11),int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [68]:
np.ones(1000)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

In [38]:
np.ones((14),int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [29]:
np.linspace(0,7,3)

array([0. , 3.5, 7. ])

In [30]:
np.linspace(0,24,13)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20., 22., 24.])

In [39]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [45]:
np.random.rand(3,5)

array([[0.36836953, 0.98203652, 0.77984283, 0.01972465, 0.04319863],
       [0.29250654, 0.93548886, 0.67956528, 0.77879302, 0.5306125 ],
       [0.44141596, 0.5497301 , 0.43487595, 0.46913993, 0.80556974]])

In [59]:
np.random.randint(2,100)

77

In [54]:
arr=np.random.randn(3,5)
arr

array([[ 0.76055609, -0.13136467, -0.04752572,  1.26221308, -0.07471232],
       [ 0.32803169, -0.79814214, -0.91649162,  0.12484348,  0.09273313],
       [-1.09129559, -0.90742551,  0.01869338,  1.76477919, -2.56018614]])

In [55]:
np.random.randint(20,50,100)

array([44, 49, 20, 23, 39, 40, 28, 35, 24, 42, 41, 39, 35, 40, 32, 28, 32,
       36, 25, 35, 22, 23, 28, 37, 21, 38, 41, 29, 25, 36, 24, 25, 28, 34,
       24, 47, 25, 28, 49, 22, 42, 25, 27, 30, 30, 37, 47, 42, 48, 25, 49,
       28, 21, 36, 34, 44, 45, 48, 35, 41, 31, 28, 40, 30, 20, 37, 47, 37,
       48, 36, 36, 34, 39, 26, 20, 37, 35, 22, 41, 33, 48, 24, 24, 43, 29,
       20, 38, 43, 28, 31, 44, 36, 35, 49, 29, 23, 35, 39, 35, 36])

In [63]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [66]:
rand_array=np.random.randint(0,10,50)
rand_array

array([7, 5, 0, 3, 4, 8, 5, 5, 0, 3, 3, 1, 2, 9, 9, 4, 4, 2, 4, 4, 5, 6,
       3, 9, 7, 7, 5, 6, 5, 0, 1, 0, 6, 2, 9, 8, 7, 8, 6, 2, 4, 7, 7, 9,
       7, 2, 3, 1, 2, 5])

In [74]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

### above code 30nsize elements can accept